### ISSUE TITLE
Feature Request: Ignore max 0 HP NPCs

### ISSUE THREAD

**Issue by kenderbard** [Nevela-0/PF1-Improved-Conditions#3]
I really love this mod! I have a small feature request; it would be nice if it ignored NPCs who have a 0/0 HP value (aka NPCs created just to be talking faces.) Right now if I leave "Apply Disabled Condition at 0 HP" on, and drag one of these 'empty' NPCs onto the map, it gives them slowed and disabled.

**Comment by Nevela-0** [comment]
This should be fixed with v1.1
