### ISSUE TITLE
Confusion effect is not rolled per character but rather once per turn for all creatures

### ISSUE THREAD

**Issue by McGreger** [Nevela-0/PF1-Improved-Conditions#4]
Version: 1.0
Error: confusion effect is not rolled per character but rather once per turn for all creatures:

![image](https://github.com/user-attachments/assets/96f9772c-ae75-4e25-ae00-fda909d4395e)

> Roll on the following table at the **start of each subject's turn each round** to see what it does in that round.

**Comment by Nevela-0** [comment]
Confusion should now give a chat message on the token's turn as of v1.1
