### ISSUE TITLE
Can't use one handed weapons while grappled

### ISSUE THREAD

**Issue by McGreger** [Nevela-0/PF1-Improved-Conditions#5]
Version: 1.0
Error: When using a shield and a one handed weapon, using the weapon is not possible. 

by rules on two-handed weapons can't be used while grappled

**Comment by Nevela-0** [comment]
This will be partially fixed.
Currently, the system doesn't give us a legitimate way of knowing whether an item or a weapon is held by one or more hands. The held property only controls the ability multiplier which is a good indication but doesn't cover ranged weapons.
I will work on a more robust way of handling those in the future.
