### ISSUE TITLE
Autocollapse chat cards blocks Confusion descriptions

### ISSUE THREAD

**Issue by Damuth1977** [Nevela-0/PF1-Improved-Conditions#7]
Foundry v11.315 (self-hosted)
PF1e 10.7
Mods active: PF1-Improved-Conditions & Socketlib

When an actor is confused, I get a message in the chat when his turn comes around.  However: I have the setting on that autocollapses all chatcards.  The messages I get cannot be 'uncollapsed' in the chat and so I can't see what the exact effect is.  I get no errors in the console.  When I turn of the auto-collapse setting, everything works as expected.

**Comment by Nevela-0** [comment]
Should be fixed with v1.2
