### ISSUE TITLE
Apply Dead Condition not working

### ISSUE THREAD

**Issue by SkeithM** [Nevela-0/PF1-Improved-Conditions#8]
Tested with Pf1e v 10.7
Improved conditions 1.1

Apply Dead Condition  at Negative consitution HP doesn't seem to work and is throwing up an error.

![image](https://github.com/user-attachments/assets/22e7d96a-1251-44b6-a057-35ccf27a4269)

**Comment by Nevela-0** [comment]
Should be fixed with v1.2
